<!-- application/modules/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Oauthwo Authorization Server</title>
  <?php echo $this->headStyle(); ?>
  <?php //echo $this->headLink()->appendStylesheet('/css/global.css') ?>
  <?php //$this->headLink()->appendStylesheet('https://code.jquery.com/ui/1.8.2/themes/smoothness/jquery-ui.css') ?>
  <?php //echo $this->headLink(); ?>
  <?php //$this->addHelperPath('ZendX/JQuery/View/Helper/', 'ZendX_JQuery_View_Helper'); $this->jQuery()->setCdnSsl(true); ?>
  <?php //echo $this->JQuery()->setVersion('1.4.2')->setUiVersion('1.8.2'); ?>
</head>
<body>
<div id="header" style="background-color: #EEEEEE; height: 30px;">
    <div id="header-logo" style="float: left">
        <b>OAuthwo Authorization Server</b>
    </div>
</div>
    <?php if (Zend_Auth::getInstance()->hasIdentity()): ?>
    <div id="header-navigation" style="height:20px;">
        
        <span style="float:left;">
            Welcome <?=Zend_Auth::getInstance()->getIdentity()?>
        </span>
        <a href="<?php echo $this->url(
            array('controller'=>'login','action'=>'logout'),
            'default',true) ?>" style="float: right;">Logout</a>
        
    </div>    
    <?php endif;?>
    
 
<?php echo $this->layout()->content ?>
 
</body>
</html>
